### ISSUE TITLE
Could not insert 'it87': Device or resource busy

### ISSUE THREAD

**Issue by mariusmotea** [a1wong/it87#1]
Hi,

Any idea why i cannot load this module? I tried both dkms and regular compilation methods and the result is the same. I get the ITE device address using sensors-detect

```
Found `ITE IT8686E Super IO Sensors'                        Success!
    (address 0xa40, driver `to-be-written')
```

```
root@pve:~/it87-master# modprobe it87 force_id=0xa40
modprobe: ERROR: could not insert 'it87': No such device
```

Thanks.

**Comment by Lamieur** [comment]
I bet there's no need for DKMS - my ITE IT8688E (on a Gigabyte Z390-UD) works with in-tree driver (Linux 4.18) nicely with **force_id=0x8628**

(You're supposed to enter chip ID, not its address)

It also works with other IDs, but doesn't expose as many sensors (the motherboard has 6 zones). One voltage sensor is showing 0V, but that's to be expected from using wrong driver ;)

You should try this ID and others, just like it's written in the README on the main page ;)

**Comment by mariusmotea** [comment]
Thanks,

I tried also with the chip id but the issue in my case was solved by adding in grub config `acpi_enforce_resources=lax`.

**Comment by djkerya** [comment]
Gigabyte Z390 UD. Ubuntu 18.04 kernel 4.15.0, lm-sensors 3.4.0. My workaround confirms described actions :
I have used  acpi_enforce_resources=lax in /etc/default/grub
and after that sudo modprobe it87 force_id=0x8628
Sensors shows both my connected cpu fan and sysfan 1.

**Comment by Lamieur** [comment]
Yes, I used acpi_enforce_resources=lax already anyway, so I simply didn't think to document this here. Thanks.

And all 4 fan controllers on the Z390-UD work, saying this just in case someone in the future might misinterpret the above as only two of them working :)

**Comment by brauliobo** [comment]
same for me, `modprobe it87` only worked with `acpi_enforce_resources=lax` on arch linux 5.4

**Comment by krassswr** [comment]
> I bet there's no need for DKMS - my ITE IT8688E (on a Gigabyte Z390-UD) works with in-tree driver (Linux 4.18) nicely with **force_id=0x8628**
> 
> (You're supposed to enter chip ID, not its address)
> 
> It also works with other IDs, but doesn't expose as many sensors (the motherboard has 6 zones). One voltage sensor is showing 0V, but that's to be expected from using wrong driver ;)
> 
> You should try this ID and others, just like it's written in the README on the main page ;)

I confirm that with that option I managed to make Gigabyte X570UD to start report fans speeds temperatures and voltages.
